In [2]:
import numpy as np

my_list = [1,2,3,4,5]
np.array(my_list)

array([1, 2, 3, 4, 5])

In [3]:
x = np.zeros((3,4))

In [4]:
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
print("dtype:",x.dtype)

dtype: float64


In [7]:
x = np.ones((4,3))

In [8]:
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
x = np.full((4,3),5)

In [10]:
print(x)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [11]:
print(x.dtype)

int32


In [12]:
x = np.eye(5)

In [13]:
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
x = np.diag([10,20,30,40])

In [15]:
print(x)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


In [16]:
x = np.arange(10)

In [17]:
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
x = np.arange(4,9,2)

In [21]:
print(x)

[4 6 8]


In [23]:
x = np.linspace(0,25,10)

In [24]:
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [26]:
x = np.linspace(0,25,10,endpoint=False)

In [27]:
print(x)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [30]:
x = np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [31]:
x = np.reshape(x,(4,5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [32]:
x = np.reshape(x,(10,2))

In [33]:
print(x)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [38]:
x = np.linspace(0,50,10,endpoint=False).reshape(5,2)

In [39]:
x = np.random.random((3,3))

In [40]:
print(x)

[[0.49653196 0.18497837 0.07045673]
 [0.18046697 0.08244742 0.38918701]
 [0.14734142 0.76232603 0.78228236]]


In [44]:
x = np.random.randint(4,15,(3,2))

In [45]:
print(x)

[[8 9]
 [6 6]
 [8 7]]


In [46]:
x = np.random.normal(0,0.1,size=(1000,1000))
print(x)

[[-0.07917568 -0.0785877   0.11986313 ...  0.00109002  0.01757484
   0.00630062]
 [-0.1014289   0.12826653  0.07182683 ...  0.06870391 -0.07596487
   0.03181352]
 [-0.09007015  0.16970775  0.04207962 ... -0.04044275  0.07855951
  -0.00610868]
 ...
 [-0.04066202 -0.12088307  0.10314344 ...  0.06335709 -0.06553991
   0.08429237]
 [ 0.10042283  0.1218973  -0.12010156 ...  0.02066864 -0.10166277
   0.03535919]
 [-0.07408566 -0.09763558  0.0582946  ... -0.10343485  0.09579988
   0.09754897]]


In [47]:
print("means:",x.mean())
print("std:",x.std())
print("max:",s.max())
print("min:",s.min())
print("positive:",(x>0).sum())
print("negative",(x<0).sum())

means: 4.676270976643001e-05
std: 0.0999641765078574


NameError: name 's' is not defined