In [4]:
import numpy as np


In [6]:
x= np.array([1,2,3,4,5])

In [7]:
print(type(x))

<class 'numpy.ndarray'>


In [8]:
print(x)

[1 2 3 4 5]


In [9]:
x.dtype

dtype('int32')

In [10]:
x.shape

(5,)

In [15]:
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
y.shape

(3, 3)

In [14]:
y.size

9

In [16]:
x = np.array(["Hello","yes"])

In [17]:
print("shape:",x.shape)
print("type:",type(x))
print("dtype:",x.dtype)

shape: (2,)
type: <class 'numpy.ndarray'>
dtype: <U5


In [24]:
t= np.array([[1,2,3],["r","t"]])

ValueError: setting an array element with a sequence.

In [21]:
print(t,t.dtype)

[list([1, 2, 3]) list(['r', 't'])] object
